### PR TITLE
PyTorch Implementation of SRGAN

### PR DESCRIPTION
**Pull request by saqibns**
Trained on 256x256 images with an upscale factor of 2.

### CODE REVIEW

**Comment by saqibns** [comment]
Thanks for taking the time to review the code, Erick!

I'm glad you mentioned the point about examples. I'll add a few. It works well on the data similar to what it has been trained on. However, for our data (which is quite different), it produces strange artifacts. I'll add some examples of those too.

**Comment by wave911** [comment]
Looks fine for me. One quick question-can this code be used for additional images generation? We don’t have enough images for wheat type

**Comment by saqibns** [comment]
Yes, some parts of it can be used for data generation. The entire GAN part is usable, it's just that the inputs will have to change from low-resolution images to noise tensors.

**Comment by jamestjw** [comment]
Good thinking Alex, we should definitely try that. Though there is one concern, since we ourselves can't tell if there's wheat in the images, we might have a hard time assessing our model.

**Comment by saqibns** [comment]
Thanks, guys for your time and inputs!

After Alex's comment, Praneeth and I had a discussion using the SRGAN architecture for generating images. I think it can be used as is. We just need to remove the content loss (and maybe mse loss too) and we can train the entire architecture to generate images we want. We can provide 256x256 noise input and train it to generate 512x512 images. 

And yes, James' comment makes sense too. Do rice and wheat have different signatures in some other band (or their combination)? If so, would multi-spectral image generation be of help?

**Pull request merged**
